package com.github.mkopylec.charon.test

import com.github.mkopylec.charon.test.specification.AfterServerNameRequestHeadersRewriterBasicSpec

class AfterServerNameRequestHeadersRewriterSpec extends AfterServerNameRequestHeadersRewriterBasicSpec {
}
